In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
a


tensor([[1.3279e-30, 0.0000e+00, 0.0000e+00],
        [1.5046e-36, 1.3313e-34, 0.0000e+00]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(6,3)

tensor([[0.0653, 0.6867, 0.7206],
        [0.2465, 0.3758, 0.8524],
        [0.5274, 0.3284, 0.4218],
        [0.7585, 0.2010, 0.3928],
        [0.1168, 0.4981, 0.0633],
        [0.8397, 0.8862, 0.5705]])

In [ ]:
# manual_seed
torch.manual_seed(500)
torch.rand(2,3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [ ]:
torch.manual_seed(500)
torch.rand(4,5)

tensor([[0.5820, 0.1338, 0.7995, 0.3071, 0.6526],
        [0.6105, 0.1575, 0.6983, 0.7883, 0.7981],
        [0.4593, 0.8997, 0.2518, 0.5648, 0.0302],
        [0.5930, 0.6386, 0.4795, 0.6030, 0.7351]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,7))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

Creating tensors in different ways
torch.tensor([[1,2,3],[4,5,6]])


Creates a tensor from a Python list.
Shape → (2, 3) (2 rows, 3 columns).

torch.arange(0, 10, 2)


Creates numbers from 0 to 10 (excluding 10) with a step of 2.
Output → 0, 2, 4, 6, 8
Useful when you want evenly spaced values like loops.

torch.linspace(0, 10, 10)


Creates 10 equally spaced values between 0 and 10 (including both).
Useful in math, plotting, and ML experiments.

torch.eye(5)


Creates a 5 × 5 identity matrix
Diagonal values = 1, rest = 0
Very useful in linear algebra.

torch.full((3, 3), 5)


Creates a 3 × 3 tensor filled with 5
Good when you want constant values.

Tensor shape
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape


Output → torch.Size([2, 3])
Means 2 rows and 3 columns.

Creating tensors with the same shape as another tensor
torch.empty_like(x)


Creates a tensor with same shape as x, but values are random garbage (uninitialized).
Fast, but values are meaningless.

torch.zeros_like(x)


Creates a tensor with same shape as x, filled with 0s.

torch.ones_like(x)


Creates a tensor with same shape as x, filled with 1s.

torch.rand_like(x, dtype=torch.float32)


Creates a tensor with same shape as x, filled with random values between 0 and 1, and data type set to float32.



In [ ]:
x = torch.tensor([[7,2,3],[4,5,6]])
x

tensor([[7, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[214748364844, 219043332140, 188978561117],
        [223338299483, 227633266732, 231928234028]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1752, 0.3647, 0.7076],
        [0.5423, 0.4054, 0.2785]])

## Tensor Data Types

In [ ]:
# find data type formate : "name of tensor.dtype"
x.dtype

torch.int64

In [ ]:
# assign data type (changes the data type from one to another or can say forces)
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[7., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7401, 0.8357],
        [0.8930, 0.7457]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5477, 0.6984],
        [0.7974, 0.5561]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0127, 0.0365, 0.2741],
        [0.3844, 0.0983, 0.3907]])
tensor([[0.0576, 0.9708, 0.4193],
        [0.5885, 0.3833, 0.3003]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0127, 0.0365, 0.2741],
        [0.3844, 0.0983, 0.0905]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 9., 1.],
        [9., 7., 9.]])

In [ ]:
torch.sum(e, dim=0)

tensor([18., 16., 10.])

In [ ]:
# sum
torch.sum(e)
# sum along columns

# sum along rows


tensor(44.)

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([9., 8., 5.])

In [ ]:
# median
torch.median(e)

tensor(9.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(45927.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.2042)

In [ ]:
# variance
torch.var(e)

tensor(10.2667)

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 0, 8],
        [4, 9, 3]])
tensor([[0, 3],
        [0, 8],
        [1, 3]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 8, 36],
        [ 3, 93]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 4],
        [0, 9],
        [8, 3]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 1., 5.],
        [9., 6., 9.],
        [9., 2., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(-90.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2667, -0.0333,  0.2333],
        [-0.2000,  0.2667, -0.2000],
        [ 0.4000, -0.0333, -0.1000]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 2, 7],
        [7, 7, 7]])
tensor([[2, 8, 4],
        [1, 2, 7]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True,  True,  True],
        [ True,  True, False]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 7.],
        [2., 7., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 1.9459],
        [0.6931, 1.9459, 0.6931]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 1.0966e+03],
        [7.3891e+00, 1.0966e+03, 7.3891e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.0000, 2.6458],
        [1.4142, 2.6458, 1.4142]])

In [ ]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.9991],
        [0.8808, 0.9991, 0.8808]])

In [ ]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(k, dim=0)

tensor([[0.1192, 0.0474, 0.9933],
        [0.8808, 0.9526, 0.0067]])

In [ ]:
# relu


## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7124, 0.0497, 0.5176],
        [0.2079, 0.1081, 0.4662]])
tensor([[0.7323, 0.1051, 0.8843],
        [0.1797, 0.8918, 0.4960]])


In [ ]:
m.add_(n)

tensor([[1.4447, 0.1549, 1.4019],
        [0.3876, 0.9999, 0.9622]])

In [ ]:
m

tensor([[1.4447, 0.1549, 1.4019],
        [0.3876, 0.9999, 0.9622]])

In [ ]:
n

tensor([[0.7323, 0.1051, 0.8843],
        [0.1797, 0.8918, 0.4960]])

In [ ]:
torch.relu(m)

tensor([[1.4447, 0.1549, 1.4019],
        [0.3876, 0.9999, 0.9622]])

In [ ]:
m.relu_()

tensor([[1.4447, 0.1549, 1.4019],
        [0.3876, 0.9999, 0.9622]])

In [ ]:
m

tensor([[1.4447, 0.1549, 1.4019],
        [0.3876, 0.9999, 0.9622]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.2020, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.2020, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
b

tensor([[0.0000, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
id(a)

133348681935488

In [ ]:
id(b)

133348681935488

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
b

tensor([[0.0000, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.5250,  0.2228],
        [ 0.2953,  0.6597,  0.8825]])

In [ ]:
b

tensor([[0.0000, 0.5250, 0.2228],
        [0.2953, 0.6597, 0.8825]])

In [ ]:
id(a)

133348681935488

In [ ]:
id(b)

133348731131920